### PR TITLE
Change types: stricter Integer cast, make errors user-friendly

### PR DESCRIPTION
**Pull request by cristina23**
When validating/casting an Integer, use Integer(<string>) instead of
<string>.to_i in order to raise an error in case it's a float.
Make the error message more user-friendly, and print the rest in the log.

For task: https://schaffner.prod.radar.lan/issues/2485

### CODE REVIEW

**Comment by andreas-kopecky** [comment]
An interesting change :) 

Personally i would have made the error messages better, by raising a custom error with a meaningful message in the actual :integer type cast. That way you do not need to track "original_type" and can actually use more flexible messages (createing a CIDR for instance can fail with more than one different error message - like "invalid broadcast part", "invalid bit mask", etc. pp)

Also this introduces asymmetric behavior between :integer and :float although i guess that is acceptable.

In general i really need to remember to read this ticket tomorrow - i am dead curious why accepting integer strings for int values is an issue :rabbit:

**Comment by cristina23** [comment]
Sebastian says you should talk to him tomorrow about this.

**Comment by simonrepp** [comment]
Looks good to me, I think Bndy wants to have another look, he's dead curious :)

**Comment by rs-sweiss** [comment]
yeah, spoke with bndy, he accepts that i am lazy

**Pull request merged**
